version: '3.3'

services:
    spricalback:
        build: .
        container_name: "spricalback"
        image: debian/latest
        ports:
            - 3000:3000
        links:
            - mongodb
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
          - MONGODB_USER="" 
          - MONGODB_PASS=""
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
